### ISSUE TITLE
removePackageDependencies doesn't remove if there are multiple dependency types

### ISSUE THREAD

**Issue by dptoot** [sindresorhus/write-package#23]
Passing the dependency array within an object seems to not remove the dependency

// does not work
`
await removePackageDependencies({
    dependencies: [
        'myDependency'
    ]
});
`

// works
`
await removePackageDependencies([
    'myDependency'
]);
`

**Comment by sindresorhus** [comment]
// @tommy-mitchell

**Comment by sindresorhus** [comment]
We are unable to reproduce this. Can you share the package.json that reproduces the issue?

**Comment by stekovinbranturry** [comment]
hi @sindresorhus, I also have this issue, please help to review my pr
